import type { Metadata } from 'next'
import localFont from 'next/font/local'

import './globals.css'
import HeaderComp from './components/layout/header'

export const lemonmilk = localFont({
  src: './resources/fonts/lemonmilk.woff2', // Path relative to this file
  variable: '--font-lemonmilk', // CSS variable name for Tailwind
  display: 'swap', // Improves performance
})

export const ruminate = localFont({
  src: './resources/fonts/ruminate.woff2', // Path relative to this file
  variable: '--font-ruminate', // CSS variable name for Tailwind
  display: 'swap', // Improves performance
})

export const metadata: Metadata = {
  title: 'MeTube',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${lemonmilk.variable} ${ruminate.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <HeaderComp />
        {children}
      </body>
    </html>
  )
}
